### ISSUE TITLE
Opening discussions on this repo

### ISSUE THREAD

**Issue by verkaro** [RealMelkor/Gemigit#1]
I am a non-coding end user. But Gemigit is very good from my perspective. An end user like me needs a place to ask questions -- like: is LFS planned to be supported? and such.

I enjoy using Soft-Serve https://github.com/charmbracelet/soft-serve , however, because my primary interest is developing content for Gemini Space, I find the Gemigit TUI a better and more capable fit. I would be glad to promote this software to end users in my humble circle of influence. Especially appreciated is that you wrote this in Go. I find Go to be reasonably trivial to compile and update. All in all the design choices here are brilliant.

So forgive me posting this issue. It is really a request and praise that is best made through a discussions channel.

Good work!

**Comment by RealMelkor** [comment]
Thanks, I guess I could add my email address at the bottom of the README and maybe create an IRC channel on libera.chat if the user base grow large enough. Also for feature requests, I think people could simply create an issue on github with the label "enhancement".

**Comment by verkaro** [comment]
I believe it is an option built into GitHub, a preference called discussions, somewhere. But whatever works best for you.

**Comment by RealMelkor** [comment]
ah sure, I didn't know it was a Github thing. It's enabled now.
