### ISSUE TITLE
server fails with config users: registration: false 

### ISSUE THREAD

**Issue by verkaro** [RealMelkor/Gemigit#2]
Hi,
I assume that the purpose of having the option to disable users registration is for a private (or closed circle) git service. However if I change the config to registration: false the server fails to restart.

I am using a debian 11 server.

**Comment by RealMelkor** [comment]
It should work now with the last commit. It was caused by the configuration file parser not recognizing false as a valid value.

**Comment by verkaro** [comment]
Just tried it. Thank you. It works fine.
